-- worksheet 1
BEGIN TRANSACTION; -- 1
SHOW TRANSACTIONS; -- 2
SELECT * FROM table_locks; -- 5
SHOW LOCKS; -- 6
COMMIT; -- 9
SHOW TRANSACTIONS; -- 10

-- worksheet 2
BEGIN TRANSACTION; -- 3
SHOW TRANSACTIONS; -- 4
SELECT * FROM table_locks; -- 7
SHOW LOCKS; -- 8
COMMIT; -- 11
SHOW TRANSACTIONS; -- 12
